#!/bin/bash
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV01_170818
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV02_170815
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV03_170818
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV04_170907
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV05_170912
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV06_170913
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV07_170914
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV08_170922
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV09_171204
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV10_171213
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV11_171208
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV12_171211
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV13_180127
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV14_180128
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV15_180205
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV16_180206
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV17_180207
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV18_180208
sbatch ./SSOptimizejob.bash  /gpfs/data/buzsakilab/DL/YSData/YutaData/YMV19_180209